services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: subquerynetwork/subql-node-cosmos:v3.12.0
    pull_policy: if_not_present
    depends_on: ['postgres']
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --db-schema=app
      - --workers=4
      - --batch-size=30
      # - --log-level=debug
      # - --unfinalized-blocks=true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:v2.13.0
    pull_policy: if_not_present
    ports:
      - 3000:3000
    depends_on:
      - 'postgres'
      - 'subquery-node'
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000

  agd:
    image: ghcr.io/agoric/agoric-3-proposals:latest
    pull_policy: if_not_present
    platform: linux/amd64
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
    environment:
      DEST: 1
      DEBUG: 'SwingSet:ls,SwingSet:vat'
    volumes:
      - .:/workspace
    entrypoint: ['bash', '-c']
    command: >
      chmod +x /workspace/scripts/run-chain.sh &&
      /workspace/scripts/run-chain.sh ||
      echo 'Failed to execute run-chain.sh, checking environment and permissions' &&
      ls -la /workspace/scripts &&
      env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:26657/status']
      interval: 5s
      timeout: 10s
      retries: 5
