name: 'Place Bids'
description: 'Place bids by price or discount'
inputs:
  fromAddress:
    description: 'Address from which the bid is made'
    required: true
  giveAmount:
    description: 'Amount to offer in the bid'
    required: true
  priceOrDiscount:
    description: 'Price or discount to apply to the bid'
    required: true
  commandType:
    description: 'Type of command to execute (by-price or by-discount)'
    required: true
  agoricNet:
    description: 'Agoric network configuration'
    required: true
  commandTimeout:
    description: 'Maximum time in seconds for the command to complete'
    required: true
  containerName:
    description: 'Name of the Docker container where the commands will be executed'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Place Bid
      shell: bash
      run: |
        if [ "${{ inputs.commandType }}" == "by-price" ]; then
          commandType="bid by-price --price"
        elif [ "${{ inputs.commandType }}" == "by-discount" ]; then
          commandType="bid by-discount --discount"
        fi

        command="/usr/src/agoric-sdk/packages/agoric-cli/bin/agops inter ${commandType} \"${{ inputs.priceOrDiscount }}\" --from \"${{ inputs.fromAddress }}\" --give \"${{ inputs.giveAmount }}\" --keyring-backend=test"
        echo "Executing command in the container..."
        docker exec ${{ inputs.containerName }} /bin/bash -c "env AGORIC_NET=${{ inputs.agoricNet }} timeout ${{ inputs.commandTimeout }} $command"
