name: Liquidation Testing
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start A3P container
        run: docker run -d -p 26657:26657 -p 1317:1317 -p 9090:9090 --name a3p ghcr.io/agoric/agoric-3-proposals:latest

      - run: corepack enable
        shell: bash

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Start subql indexer
        run: yarn dev:ci

      - name: Set ATOM Price to 12.34
        run: |
          docker exec a3p /usr/src/agoric-sdk/packages/agoric-cli/bin/agops oracle setPrice --keys gov1,gov2 --pair ATOM.USD --price 12.34 --keyring-backend=test

      - name: Create Vault with 100 Minted and 15 Collateral
        uses: ./.github/actions/createVault
        with:
          wantMinted: '100'
          giveCollateral: '15'
          userKey: 'user1'
          agoricNet: 'local'
          commandTimeout: '120'
          containerName: 'a3p'

      - name: Create Vault with 103 Minted and 15 Collateral
        uses: ./.github/actions/createVault
        with:
          wantMinted: '103'
          giveCollateral: '15'
          userKey: 'user1'
          agoricNet: 'local'
          commandTimeout: '120'
          containerName: 'a3p'

      - name: Create Vault with 105 Minted and 15 Collateral
        uses: ./.github/actions/createVault
        with:
          wantMinted: '105'
          giveCollateral: '15'
          userKey: 'user1'
          agoricNet: 'local'
          commandTimeout: '120'
          containerName: 'a3p'
