name: PR
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Before setup-node because that action runs `yarn cache dir`. See https://github.com/actions/setup-node/issues/480#issuecomment-1915448139
      - run: corepack enable
        shell: bash

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install
      - run: yarn prettier:check

      - name: Run Dev
        run: |
          yarn dev
        env:
          AGORIC_NET: docker

      # # Runtime tests using the db
      # - name: Enable btree btree_gist
      #   run: psql "postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_DATABASE" -c "CREATE EXTENSION IF NOT EXISTS btree_gist;"

      - name: Run tests with Subquery Node
        env:
          TZ: UTC # prevents: Environment Timezone is not set to UTC. This may cause issues with indexing or proof of index
        run: yarn subql-node-cosmos test -f ${{ github.workspace }}
